<div>
    <x-thead.gray-50>
        <tr>
            <x-td>商品編號</x-td>
            <x-td>商品名稱</x-td>
            <x-td>刊登者</x-td>
            <x-td>刊登時間</x-td>
            <x-td>最後修改時間</x-td>
            <x-td>檢舉次數</x-td>
            <x-td>操作</x-td>
            <x-td>狀態</x-td>
        </tr>
    </x-thead.gray-50>
</div>
