<div>
    <x-thead.gray-50>
        <tr>
            <x-th.name>商品名稱</x-th.name>
            <x-th.name>檢舉原因</x-th.name>
            <x-th.name>自定義原因</x-th.name>
            <x-th.name>檢舉人</x-th.name>
            <x-th.name>檢舉日期</x-th.name>
        </tr>
    </x-thead.gray-50>
</div>
