<div>
    <x-thead.gray-50>
        <tr>
            <x-name>商品名稱</x-name>
            <x-name>檢舉原因</x-name>
            <x-name>自定義原因</x-name>
            <x-name>檢舉人</x-name>
            <x-name>檢舉日期</x-name>
        </tr>
    </x-thead.gray-50>
</div>
