<div>
    <x-thead.gray-50>
        <tr>
            <x-th.name>選擇</x-th.name>
            <x-th.name>名稱</x-th.name>
            <x-th.name>Email</x-th.name>
        </tr>
    </x-thead.gray-50>
</div>
