<div>
    <x-thead.gray-50>
        <tr>
            <x-th.name>用戶名稱</x-th.name>
            <x-th.name>檢舉</x-th.name>
            <x-th.name>權限</x-th.name>
            <x-th.name>停用</x-th.name>
        </tr>
    </x-thead.gray-50>
</div>
