<div>
    <x-thead.gray-50>
        <tr>
            <x-name>用戶名稱</x-name>
            <x-name>檢舉</x-name>
            <x-name>權限</x-name>
            <x-name>停用</x-name>
        </tr>
    </x-thead.gray-50>
</div>
